FROM postgres:latest

ARG POSTGRES_DB_NAME
ARG POSTGRES_USERNAME
ARG POSTGRES_PWD

ENV POSTGRES_USER=${POSTGRES_USERNAME}
ENV POSTGRES_PASSWORD=${POSTGRES_PWD}
ENV POSTGRES_DB=${POSTGRES_DB_NAME}

EXPOSE 5432
