[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "pgvector>=0.3.6",
    "psycopg2>=2.9.10",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
]
